##AnsibleFile Configuration file for Ubuntu Server
- hosts: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  tasks: 
#Install Docker Stack
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker Repository
      apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
            state: present
            filename: docker
            mode: 0600

    - name: Install Docker Engine.
      apt: 
         name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-compose

    - name: Enable service docker, and enable persistently
      service: 
            name: docker
            enabled: yes


