##AnsibleFile Configuration file for Ubuntu Server
- hosts: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  vars:
    new_user: oci_manager
    server_hostname: oci-ubuntu-test-ansible

  tasks: 
#Change server hostname,  change VARS before running
    - hostname: name={{ server_hostname }}

#Create new user account, change VARS before running
    - name: creating the user {{ new_user }}.
      user:
        name: "{{ new_user }}"
        createhome: yes
        shell: /bin/bash
        append: yes
        state: present  

#Remove SWAP File and disable..Requirement for Docker/K8S
    - name: Make the Swap inactive
      command: swapoff -a
    
    - name: Remove Swap entry from /etc/fstab.
      lineinfile:
       dest: /etc/fstab
       regexp: swap
       state: absent

#Install Docker Stack
    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker Repository
      apt_repository:
            repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
            state: present
            filename: docker
            mode: 0600

    - name: Install Docker Engine.
      apt: 
         name:
            - docker-ce
            - docker-ce-cli
            - containerd.io
            - docker-compose

    - name: Enable service docker, and enable persistently
      service: 
            name: docker
            enabled: yes

#Install other application
    - name: Install other application.
      apt: 
        name:
            - tree
            - git
            - wget

#Install NetData 
    - name: Install NetData Real-Time monitoring
      become: yes
      apt:
        name: netdata
        state: latest

  handlers:
    - name: Service Enable NetData
      become: yes
      service:
        name: netdata
        enabled: yes

    - name: Service Start NetData
      become: yes
      service:
        name: netdata
        state: started


