##AnsibleFile Configuration file for Ubuntu Server
- hosts: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh
  vars:
    new_user: oci_manager
    server_hostname: oci-ubuntu-test-ansible

  tasks: 
#Change server hostname,  change VARS before running
    - hostname: name={{ server_hostname }}

#Create new user account, change VARS before running
    - name: creating the user {{ new_user }}.
      user:
        name: "{{ new_user }}"
        createhome: yes
        shell: /bin/bash
        append: yes
        state: present  

#Remove SWAP File and disable..Requirement for Docker/K8S
    - name: Make the Swap inactive
      command: swapoff -a
    
    - name: Remove Swap entry from /etc/fstab.
      lineinfile:
       dest: /etc/fstab
       regexp: swap
       state: absent
       
#Install other application
    - name: Install other application.
      apt: 
        name:
            - tree
            - git
            - wget

#Install NetData 
    - name: Install NetData Real-Time monitoring
      become: yes
      apt:
        name: netdata
        state: latest

  handlers:
    - name: Service Enable NetData
      become: yes
      service:
        name: netdata
        enabled: yes

    - name: Service Start NetData
      become: yes
      service:
        name: netdata
        state: started


